### ISSUE TITLE
BERT-large (MIMIC)?

### ISSUE THREAD

**Issue by drussellmrichie** [uf-hobi-informatics-lab/ClinicalTransformerNER#15]
Hi, thank you for releasing this excellent resource. I'm wondering if you have released BERT-Large (MIMIC)? The model [here](https://transformer-models.s3.amazonaws.com/mimiciii_roberta_10e_128b.zip) only has 12 layers so must be BERT-base? Am I missing something?

**Comment by bugface** [comment]
All mimic models are pretrained with the base version of the transformer models.  We do not use bert-large because of limited computing resources.

**Comment by drussellmrichie** [comment]
Oops, sorry, I got confused between your paper and this [one](https://academic.oup.com/jamia/article/26/11/1297/5527248?casa_token=SnYZfA-uvMUAAAAA:K1jkvJBV_9-uCRaMtUHa-L2cMN-4rOkpqpoiVfu8uF7NVrysv6pZcJEaR2N41sQ2xKpIa-Tj6rKj). My mistake!
