### ISSUE TITLE
Pretraining  transformer models on MIMIC with large setting

### ISSUE THREAD

**Issue by bugface** [uf-hobi-informatics-lab/ClinicalTransformerNER#16]
we only have MIMIC model using transformer-base models,  we need to pretrain large version as well

- bert large
- roberta large
- albert - xxlarege
- xlent large
- longformer large

**Comment by bugface** [comment]
@nvbic Can you take a look on how to pretrain large bert on mimic?

**Comment by nvbic** [comment]
I will have a look.

**Comment by bugface** [comment]
we will update the roberta-large and bert-large mimic pretrained models shortly
